# Logging level.
log_level: TRACE
# Matrix request timeout (in seconds).
request_timeout: 10
# Login information.
login:
  # Homeserver
  home_server: https://matrix.org
  # Username
  user: some-user
  # Password
  password: some-password
# Access control to the bot.
access:
  # Administrators with full access, including invite rights.
  admins:
    - "@some-use:matrix.org"
  # Moderators with access to using commands only.
  mods: []
# Store paths
store:
  # Location of matrix state-store.
  state_store: "./data/state"
  # Passphrase of the state stores.
  passphrase: "password"
  # Path of job runner database.
  job_runner_db: "./data/jobs"
  # Path of the bot's database.
  database: "./data/bot"
# Intervalled execution configuration.
intervals:
  # Number of seconds of the interval duration for RSS feed checks.
  rss: 600
